/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital_Mgt_System;


import java.sql.*;
import javax.swing.JOptionPane;

import java.awt.Color;


/**
 *
 * @author Saad
 */
public class Admin extends javax.swing.JFrame {

    sahidb dbobj=new sahidb();
    public Admin() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        rqual = new javax.swing.JTextField();
        rcontact = new javax.swing.JTextField();
        raddress = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addReceptionist = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        dqual = new javax.swing.JTextField();
        dcontact = new javax.swing.JTextField();
        daddress = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jAddDoctor = new javax.swing.JButton();
        combobox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jAppointedAs = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        appointedAs = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        pqual = new javax.swing.JTextField();
        pcontact = new javax.swing.JTextField();
        paddress = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        addPharma = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        adminInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Receptionist's Name :");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Contact :");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Qualification :");

        rname.setForeground(new java.awt.Color(183, 183, 183));
        rname.setText("Enter Name");
        rname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rnameMouseClicked(evt);
            }
        });
        rname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rnameKeyTyped(evt);
            }
        });

        rqual.setForeground(new java.awt.Color(183, 183, 183));
        rqual.setText("Enter Qualification");
        rqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rqualMouseClicked(evt);
            }
        });
        rqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rqualActionPerformed(evt);
            }
        });
        rqual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rqualKeyTyped(evt);
            }
        });

        rcontact.setForeground(new java.awt.Color(183, 183, 183));
        rcontact.setText("Enter Contact Number");
        rcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rcontactMouseClicked(evt);
            }
        });
        rcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rcontactKeyTyped(evt);
            }
        });

        raddress.setForeground(new java.awt.Color(183, 183, 183));
        raddress.setText("Enter Address");
        raddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raddressMouseClicked(evt);
            }
        });
        raddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                raddressKeyTyped(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        addReceptionist.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addReceptionist.setText("Add Receptionist");
        addReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReceptionistActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel16.setText("(+92)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addReceptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(24, 24, 24)
                                        .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(119, 119, 119)
                                        .addComponent(raddress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(rqual, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(rname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rqual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addReceptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receptionist", jPanel1);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Doctor's Name :");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Contact :");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setText("Address :");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setText("Qualification :");

        dname.setForeground(new java.awt.Color(183, 183, 183));
        dname.setText("Enter Name");
        dname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dnameMouseClicked(evt);
            }
        });
        dname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dnameKeyTyped(evt);
            }
        });

        dqual.setForeground(new java.awt.Color(183, 183, 183));
        dqual.setText("Enter Qualification");
        dqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dqualMouseClicked(evt);
            }
        });
        dqual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dqualKeyTyped(evt);
            }
        });

        dcontact.setForeground(new java.awt.Color(183, 183, 183));
        dcontact.setText("Enter Contact Number");
        dcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcontactMouseClicked(evt);
            }
        });
        dcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dcontactKeyTyped(evt);
            }
        });

        daddress.setForeground(new java.awt.Color(183, 183, 183));
        daddress.setText("Enter Address");
        daddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daddressMouseClicked(evt);
            }
        });
        daddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                daddressKeyTyped(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jAddDoctor.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jAddDoctor.setText("Add Doctor");
        jAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddDoctorActionPerformed(evt);
            }
        });

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointed As", "Specialist", "Emergency Doctor" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setText("Appointed As :");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel17.setText("(+92)");

        appointedAs.setText("Appointed as");
        appointedAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointedAsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(70, 70, 70)
                                .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(119, 119, 119)
                                .addComponent(daddress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(dqual, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jAppointedAs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appointedAs, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)))
                        .addComponent(jAddDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(dcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(dqual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jAddDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAppointedAs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appointedAs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 777, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctor", jPanel3);

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel36.setText("Pharmacist's Name :");

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel37.setText("Contact :");

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel38.setText("Address :");

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel39.setText("Qualification :");

        jTextField28.setForeground(new java.awt.Color(183, 183, 183));
        jTextField28.setText("Enter Name");
        jTextField28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField28MouseClicked(evt);
            }
        });
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField28KeyTyped(evt);
            }
        });

        pqual.setForeground(new java.awt.Color(183, 183, 183));
        pqual.setText("Enter Qualification");
        pqual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pqualMouseClicked(evt);
            }
        });
        pqual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pqualKeyTyped(evt);
            }
        });

        pcontact.setForeground(new java.awt.Color(183, 183, 183));
        pcontact.setText("Enter Contact Number");
        pcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcontactMouseClicked(evt);
            }
        });
        pcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pcontactKeyTyped(evt);
            }
        });

        paddress.setForeground(new java.awt.Color(183, 183, 183));
        paddress.setText("Enter Address");
        paddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paddressMouseClicked(evt);
            }
        });
        paddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paddressKeyTyped(evt);
            }
        });

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        addPharma.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        addPharma.setText("Add Pharmacist");
        addPharma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPharmaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel18.setText("(+92)");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(pqual, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addPharma, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(37, 37, 37)
                                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(119, 119, 119)
                                        .addComponent(paddress, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(pcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(paddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(pqual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(addPharma, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pharmacist", jPanel2);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        jLabel2.setText("Admin");

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setText("Admin Name :");

        jLabel5.setText("Admin Info :");

        adminInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(adminInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(adminInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int a,b,c,d,e,f,g,h,i,j,k,l=0;
Object selectedItemAppointed;
String AppointedAs;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        First_Page pg=new First_Page();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void adminInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminInfoActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
      appointedAs.setText(combobox.getSelectedItem().toString()); 
    }//GEN-LAST:event_comboboxActionPerformed

    private void rqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rqualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rqualActionPerformed

    private void rnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnameKeyTyped
         char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||rname.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_rnameKeyTyped

    private void rcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rcontactKeyTyped
          char c=evt.getKeyChar();
       if(!(Character.isDigit(c))||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||rcontact.getText().length()>=10){
       evt.consume();
       getToolkit().beep();
       }// TODO add your handling code here:
    }//GEN-LAST:event_rcontactKeyTyped

    private void raddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_raddressKeyTyped
         char c=evt.getKeyChar();
       if(c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||raddress.getText().length()>=50){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_raddressKeyTyped

    private void rqualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rqualKeyTyped
           char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||rqual.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       }// TODO add your handling code here:
    }//GEN-LAST:event_rqualKeyTyped

    private void rnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rnameMouseClicked
                for(int i=0;i<1;i++){
            
    while(a==0){
    rname.setText("");
    this.rname.setForeground(Color.black);
    a++; 
    }
 }
// TODO add your handling code here:
    }//GEN-LAST:event_rnameMouseClicked

    private void rcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rcontactMouseClicked
               for(int i=0;i<1;i++){
            
    while(b==0){
    rcontact.setText("");
    this.rcontact.setForeground(Color.black);
    b++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_rcontactMouseClicked

    private void raddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raddressMouseClicked
                for(int i=0;i<1;i++){
            
    while(c==0){
    raddress.setText("");
    this.raddress.setForeground(Color.black);
    c++; 
    }
 }// TODO add your handling code here:
    }//GEN-LAST:event_raddressMouseClicked

    private void rqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rqualMouseClicked
               for(int i=0;i<1;i++){
            
    while(d==0){
    rqual.setText("");
    this.rqual.setForeground(Color.black);
    d++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_rqualMouseClicked

    private void dnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnameKeyTyped
          char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||dname.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       }// TODO add your handling code here:
    }//GEN-LAST:event_dnameKeyTyped

    private void dcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcontactKeyTyped
            char c=evt.getKeyChar();
       if(!(Character.isDigit(c))||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||dcontact.getText().length()>=10){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_dcontactKeyTyped

    private void daddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daddressKeyTyped
          char c=evt.getKeyChar();
       if(c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||daddress.getText().length()>=50){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_daddressKeyTyped

    private void dqualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dqualKeyTyped
          char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||dqual.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       }  // TODO add your handling code here:
    }//GEN-LAST:event_dqualKeyTyped

    private void dnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dnameMouseClicked
               for(int i=0;i<1;i++){
            
    while(e==0){
    dname.setText("");
    this.dname.setForeground(Color.black);
    e++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_dnameMouseClicked

    private void dcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcontactMouseClicked
               for(int i=0;i<1;i++){
            
    while(f==0){
    dcontact.setText("");
    this.dcontact.setForeground(Color.black);
    f++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_dcontactMouseClicked

    private void daddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daddressMouseClicked
               for(int i=0;i<1;i++){
            
    while(g==0){
    daddress.setText("");
    this.daddress.setForeground(Color.black);
    g++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_daddressMouseClicked

    private void dqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dqualMouseClicked
                for(int i=0;i<1;i++){
            
    while(h==0){
    dqual.setText("");
    this.dqual.setForeground(Color.black);
    h++; 
    }
 }// TODO add your handling code here:
    }//GEN-LAST:event_dqualMouseClicked

    private void jTextField28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyTyped
           char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||jTextField28.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28KeyTyped

    private void pcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcontactKeyTyped
            char c=evt.getKeyChar();
       if(!(Character.isDigit(c))||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||pcontact.getText().length()>=10){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_pcontactKeyTyped

    private void paddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paddressKeyTyped
           char c=evt.getKeyChar();
       if(c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||paddress.getText().length()>=50){
       evt.consume();
       getToolkit().beep();
       }// TODO add your handling code here:
    }//GEN-LAST:event_paddressKeyTyped

    private void pqualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqualKeyTyped
           char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||pqual.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       } // TODO add your handling code here:
    }//GEN-LAST:event_pqualKeyTyped

    private void jTextField28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField28MouseClicked
               for(int i=0;i<1;i++){
            
    while(i==0){
    jTextField28.setText("");
    this.jTextField28.setForeground(Color.black);
    i++; 
    }
 } // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28MouseClicked

    private void pcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcontactMouseClicked
                for(int i=0;i<1;i++){
            
    while(j==0){
    pcontact.setText("");
    this.pcontact.setForeground(Color.black);
    j++; 
    }
 }// TODO add your handling code here:
    }//GEN-LAST:event_pcontactMouseClicked

    private void paddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paddressMouseClicked
                for(int i=0;i<1;i++){
            
    while(k==0){
    paddress.setText("");
    this.paddress.setForeground(Color.black);
    k++; 
    }
 }// TODO add your handling code here:
    }//GEN-LAST:event_paddressMouseClicked

    private void pqualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pqualMouseClicked
                for(int i=0;i<1;i++){
            
    while(l==0){
    pqual.setText("");
    this.pqual.setForeground(Color.black);
    l++; 
    }
 }// TODO add your handling code here:
    }//GEN-LAST:event_pqualMouseClicked

    private void jAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddDoctorActionPerformed
   String value = combobox.getSelectedItem().toString();
        // TODO add your handling code here:
        if(value.equals("Emergency Doctor")){
            insertEmergencyDoctor();
        }
        else if(value.equals("Specialist")){
            insertSpecialist();
        } else{
            JOptionPane.showMessageDialog(null,"error");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddDoctorActionPerformed

    private void addReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReceptionistActionPerformed
               try{
            String rname2=rname.getText();
            String rcontact2=rcontact.getText();
            String raddress2=raddress.getText();
            String rqual2=rqual.getText();
            Connection con=dbobj.getConnection();
            PreparedStatement statement=con.prepareStatement("INSERT INTO receptionists (name,password,address,contactNo,qualification) VALUES('"+rname2+"','ullu','"+raddress2+"','"+rcontact2+"','"+rqual2+"')");
            statement.executeUpdate();
        }catch(Exception e){
            System.out.println(e);
        }


    }//GEN-LAST:event_addReceptionistActionPerformed

    private void appointedAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointedAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appointedAsActionPerformed

    private void addPharmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPharmaActionPerformed
insertPharmacist();
        // TODO add your handling code here:
    }//GEN-LAST:event_addPharmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPharma;
    private javax.swing.JButton addReceptionist;
    private javax.swing.JTextField adminInfo;
    private javax.swing.JTextField appointedAs;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField daddress;
    private javax.swing.JTextField dcontact;
    private javax.swing.JTextField dname;
    private javax.swing.JTextField dqual;
    private javax.swing.JButton jAddDoctor;
    private javax.swing.JLabel jAppointedAs;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField paddress;
    private javax.swing.JTextField pcontact;
    private javax.swing.JTextField pqual;
    private javax.swing.JTextField raddress;
    private javax.swing.JTextField rcontact;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rqual;
    // End of variables declaration//GEN-END:variables
     
    public void insertSpecialist(){
         try{
            String dname2=dname.getText();
            String dcontact2=dcontact.getText();
            String daddress2=daddress.getText();
            String dqual2=dqual.getText();
            Connection con=dbobj.getConnection();
            PreparedStatement statement=con.prepareStatement("INSERT INTO specialistdoctors (name,password,address,contactNo,qualification,type) VALUES('"+dname2+"','ullu','"+daddress2+"','"+dcontact2+"','"+dqual2+"','"+appointedAs.getText()+"')");
            statement.executeUpdate();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void insertEmergencyDoctor(){
         try{
            String dname2=dname.getText();
            String dcontact2=dcontact.getText();
            String daddress2=daddress.getText();
            String dqual2=dqual.getText();
            Connection con=dbobj.getConnection();
            PreparedStatement statement=con.prepareStatement("INSERT INTO emergencydoctors (name,password,address,contactNo,qualification) VALUES('"+dname2+"','ullu','"+daddress2+"','"+dcontact2+"','"+dqual2+"')");
            statement.executeUpdate();
        }catch(Exception e){
            System.out.println(e);
        }
    }

        public void insertPharmacist(){
         try{
            String pname2=jTextField28.getText();
            String pcontact2=pcontact.getText();
            String paddress2=paddress.getText();
            String pqual2=pqual.getText();
            Connection con=dbobj.getConnection();
            PreparedStatement statement=con.prepareStatement("INSERT INTO pharmacists (name,password,address,contactNo,qualification) VALUES('"+pname2+"','ullu','"+paddress2+"','"+pcontact2+"','"+pqual2+"')");
            statement.executeUpdate();
        }catch(Exception e){
            System.out.println(e);
        }
    }

}
