/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import Hospital_Mgt_System.First_Page;
import Hospital_Mgt_System.Receptionist;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.joda.time.LocalDate;
import org.joda.time.LocalTime;

/**
 *
 * @author Saad
 */
public class Emergency extends javax.swing.JFrame {

    /**
     * Creates new form Emergency
     */
    public Emergency() {
        initComponents();
        setResizable(false);
        setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jemergencyPatientName = new javax.swing.JTextField();
        jemergencyCompanionName = new javax.swing.JTextField();
        jemergencyCompanionContact = new javax.swing.JTextField();
        jemergencyReferredDoctor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jemergencyFees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jemergencyConfirm = new javax.swing.JButton();
        jsetDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jsetTime = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jgeneratedBy = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("Generated At :");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Fee (Payable) :");

        jTextField6.setText("Date / Time");

        jCheckBox1.setText("Paid");

        jTextField7.setText("700 / Rs");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergency.png"))); // NOI18N
        jLabel2.setText("  EMERGENCY");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Patient's Name :");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Companion's Name :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Companion's Contact :");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Reffered To :");

        jemergencyPatientName.setForeground(new java.awt.Color(183, 183, 183));
        jemergencyPatientName.setText("Enter patient's Name ");
        jemergencyPatientName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemergencyPatientNameMouseClicked(evt);
            }
        });
        jemergencyPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemergencyPatientNameActionPerformed(evt);
            }
        });
        jemergencyPatientName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jemergencyPatientNameKeyTyped(evt);
            }
        });

        jemergencyCompanionName.setForeground(new java.awt.Color(183, 183, 183));
        jemergencyCompanionName.setText("Enter Companion's Name ");
        jemergencyCompanionName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemergencyCompanionNameMouseClicked(evt);
            }
        });
        jemergencyCompanionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemergencyCompanionNameActionPerformed(evt);
            }
        });
        jemergencyCompanionName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jemergencyCompanionNameKeyTyped(evt);
            }
        });

        jemergencyCompanionContact.setForeground(new java.awt.Color(183, 183, 183));
        jemergencyCompanionContact.setText("Enter Companion's Contact ");
        jemergencyCompanionContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemergencyCompanionContactMouseClicked(evt);
            }
        });
        jemergencyCompanionContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemergencyCompanionContactActionPerformed(evt);
            }
        });
        jemergencyCompanionContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jemergencyCompanionContactKeyTyped(evt);
            }
        });

        jemergencyReferredDoctor.setForeground(new java.awt.Color(183, 183, 183));
        jemergencyReferredDoctor.setText("Available Doctors");
        jemergencyReferredDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemergencyReferredDoctorMouseClicked(evt);
            }
        });
        jemergencyReferredDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemergencyReferredDoctorActionPerformed(evt);
            }
        });
        jemergencyReferredDoctor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jemergencyReferredDoctorKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel13.setText("Fee (Payable) :");

        jCheckBox2.setText("Paid");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jemergencyFees.setForeground(new java.awt.Color(183, 183, 183));
        jemergencyFees.setText("Rupees");
        jemergencyFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jemergencyFeesMouseClicked(evt);
            }
        });
        jemergencyFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jemergencyFeesKeyTyped(evt);
            }
        });

        jLabel9.setText("Slip Generated By : ");

        jemergencyConfirm.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jemergencyConfirm.setText("Confirm ");

        jsetDate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jsetDateComponentShown(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("Generated On :");

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("Generated At :");

        jsetTime.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jsetTimeComponentShown(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("(+92)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jemergencyConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jemergencyReferredDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jemergencyCompanionContact, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jemergencyCompanionName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jemergencyPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(19, 19, 19)
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jemergencyFees, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jsetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 40, Short.MAX_VALUE))
                                    .addComponent(jsetTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jgeneratedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jemergencyPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jsetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jemergencyCompanionName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jsetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jemergencyCompanionContact, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jCheckBox2)
                        .addComponent(jemergencyFees, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jemergencyReferredDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jemergencyConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jgeneratedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int a,b,c,d=0;
    private void setDate(){
        LocalTime localTime = new LocalTime();
        LocalDate localDate = new LocalDate();
        ActionListener actiondate = new ActionListener(){
            
        @Override
        public void actionPerformed(ActionEvent e){
            jsetTime.setText(LocalTime.now()+"   Hours");
            jsetDate.setText(LocalDate.now()+"");
//            java.util.Date mydate = new Date();
//            jsetDate.setText(mydate.getHours()+" : "+ mydate.getMinutes()+"   Hours" +"\n"+mydate.getDate()+"/"+mydate.getMonth()+"/"+mydate.getYear());
        }
        };
        new javax.swing.Timer(1000, actiondate).start();
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        First_Page pg=new First_Page();
        pg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Receptionist recept = new Receptionist();
        recept.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jemergencyPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemergencyPatientNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jemergencyPatientNameActionPerformed

    private void jemergencyCompanionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemergencyCompanionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemergencyCompanionNameActionPerformed

    private void jemergencyCompanionContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemergencyCompanionContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemergencyCompanionContactActionPerformed

    private void jemergencyReferredDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemergencyReferredDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemergencyReferredDoctorActionPerformed

    private void jsetDateComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jsetDateComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jsetDateComponentShown

    private void jsetTimeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jsetTimeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jsetTimeComponentShown

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jemergencyPatientNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemergencyPatientNameKeyTyped
        // TODO add your handling code here:
            char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||jemergencyPatientName.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       }
    }//GEN-LAST:event_jemergencyPatientNameKeyTyped

    private void jemergencyCompanionNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemergencyCompanionNameKeyTyped
        // TODO add your handling code here:
            char c=evt.getKeyChar();
       if(Character.isDigit(c)||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||jemergencyCompanionName.getText().length()>=27){
       evt.consume();
       getToolkit().beep();
       }
    }//GEN-LAST:event_jemergencyCompanionNameKeyTyped

    private void jemergencyCompanionContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemergencyCompanionContactKeyTyped
        // TODO add your handling code here:
            char c=evt.getKeyChar();
       if(!(Character.isDigit(c))||c=='0'||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||jemergencyCompanionContact.getText().length()>=10){
       evt.consume();
       getToolkit().beep();
       }
    }//GEN-LAST:event_jemergencyCompanionContactKeyTyped

    private void jemergencyReferredDoctorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemergencyReferredDoctorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jemergencyReferredDoctorKeyTyped

    private void jemergencyFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jemergencyFeesKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||c=='_'||c=='!'|| c=='"' || c=='#' || c=='$' || c=='%' || c=='&'|| c=='\''|| c=='('|| c==')'|| c=='*'|| c=='+'|| c=='.'|| c==','|| c=='-'|| c=='='|| c==';'|| c==':'|| c=='"'||c=='/'||c=='?'||c=='>'||c=='<'||c=='@'||c==']'||c=='['||c=='\\'||c=='~'||c=='`'||c=='^'||c=='|'||c=='{'||c=='}'||jemergencyFees.getText().length()>7){
       evt.consume();
       getToolkit().beep();
       }
    }//GEN-LAST:event_jemergencyFeesKeyTyped

    private void jemergencyPatientNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemergencyPatientNameMouseClicked
        // TODO add your handling code here:
    for(int i=0;i<1;i++){
    while(a==0){
    jemergencyPatientName.setText("");
    this.jemergencyPatientName.setForeground(Color.black);
    a++; 
    }
 }
 
    }//GEN-LAST:event_jemergencyPatientNameMouseClicked

    private void jemergencyCompanionNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemergencyCompanionNameMouseClicked
        // TODO add your handling code here:
    for(int i=0;i<1;i++){
    while(b==0){
    jemergencyCompanionName.setText("");
    this.jemergencyCompanionName.setForeground(Color.black);
    b++; 
    }
 }
 
    }//GEN-LAST:event_jemergencyCompanionNameMouseClicked

    private void jemergencyCompanionContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemergencyCompanionContactMouseClicked
        // TODO add your handling code here:
    for(int i=0;i<1;i++){
    while(c==0){
    jemergencyCompanionContact.setText("");
    this.jemergencyCompanionContact.setForeground(Color.black);
    c++; 
    }
 }
 
    }//GEN-LAST:event_jemergencyCompanionContactMouseClicked

    private void jemergencyReferredDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemergencyReferredDoctorMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jemergencyReferredDoctorMouseClicked

    private void jemergencyFeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jemergencyFeesMouseClicked
        // TODO add your handling code here:
    for(int i=0;i<1;i++){
    while(d==0){
    jemergencyFees.setText("");
    this.jemergencyFees.setForeground(Color.black);
    d++; 
    }
 }
 
    }//GEN-LAST:event_jemergencyFeesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emergency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emergency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jemergencyCompanionContact;
    private javax.swing.JTextField jemergencyCompanionName;
    private javax.swing.JButton jemergencyConfirm;
    private javax.swing.JTextField jemergencyFees;
    private javax.swing.JTextField jemergencyPatientName;
    private javax.swing.JTextField jemergencyReferredDoctor;
    private javax.swing.JLabel jgeneratedBy;
    private javax.swing.JLabel jsetDate;
    private javax.swing.JLabel jsetTime;
    // End of variables declaration//GEN-END:variables
}
